version: '3'
services:
  bot:
    image: rinna-bot
    build:
      context: .
      dockerfile: Dockerfile

    user: root
    tty: true

    ports:
      - '8888:8888'
      - '7860:7860'

    volumes:
      - ./resource:/resource
      # - ./notebook:/notebook

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]